# Default Config: https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml

config:
  warningsAsErrors: true

complexity:
  LongParameterList:
    ignoreAnnotated: ['javax.inject.Inject', 'javax.annotation.Generated', 'Composable']

formatting:
  android: true
  autoCorrect: false

# See: https://detekt.dev/docs/introduction/compose/
naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  ForbiddenComment:
    values: ['FIXME:', 'STOPSHIP:']
  MagicNumber:
    ignoreEnums: true
